# Generated by Django 2.2.4 on 2019-08-31 07:13

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_name', models.CharField(max_length=20, verbose_name='prefecture_name')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=40, verbose_name='学校名')),
                ('school_system_name', models.CharField(choices=[('PS', '小学校'), ('JS', '中学校'), ('HS', '高校'), ('UN', '大学')], max_length=10, verbose_name='school_system_name')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Prefecture')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='グループID')),
                ('group_image', models.ImageField(blank=True, default='groups/default', upload_to=groups.models.get_file_path)),
                ('group_name', models.CharField(max_length=30, verbose_name='グループ名')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Prefecture')),
                ('school_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.School')),
            ],
        ),
    ]
